[build]
  base = "frontend"
  command = "npm ci && npm run build"
  # publish the Next.js build output directory created by `next build`.
  # Publish path is relative to the `base` directory above. With `base = "frontend"`
  # the correct publish directory is the `.next` folder created by `next build`.
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
